"""
Report generation — Claude writing layer (Phase 6).

Turns the complete case file into a professional dual-audience threat-intelligence
report. Claude returns raw Markdown; the structure dict is assembled in code —
no JSON parsing of Claude's response, so no escaping fragility.

No external tools or web search — this phase reasons purely over the prior phase
outputs. A separate rendering step converts the Markdown content to PDF/Word.

CLI:
    python -m backend.app.services.report_generator --case <path_to_case_json>
"""
from __future__ import annotations

import json
import re

from ..config import settings
from .claude_client import call_claude
from .skill_loader import load_ref, load_skill


# ── prompt assembly ───────────────────────────────────────────────────────────

def _build_system_prompt() -> str:
    skill    = load_skill("report")
    template = load_ref("report_template")
    return f"{skill}\n\n---\n\n## Report Template\n\n{template}"


def _phase_summary(
    static_analysis: dict,
    dynamic_analysis: dict,
    osint: dict,
    attribution: dict,
    detection: dict,
) -> str:
    def _status(block: dict, name: str) -> str:
        return f"  - {name}: {'PRESENT' if block else 'ABSENT (phase did not run or failed)'}"

    return "\n".join([
        _status(static_analysis,  "static_analysis"),
        _status(dynamic_analysis, "dynamic_analysis"),
        _status(osint,            "osint"),
        _status(attribution,      "attribution"),
        _status(detection,        "detection"),
    ])


def _pp(obj: object) -> str:
    return json.dumps(obj, indent=2, default=str)


def _phase_block(block: dict, label: str) -> str:
    if block:
        return f"## {label}\n{_pp(block)}"
    return f"## {label}\n(not available — phase did not run or failed)"


def _build_user_message(
    static_analysis: dict,
    dynamic_analysis: dict,
    osint: dict,
    attribution: dict,
    detection: dict,
    sample_meta: dict,
) -> str:
    name   = sample_meta.get("name",   "unknown")
    sha256 = sample_meta.get("sha256", "")
    route  = sample_meta.get("route",  "unknown")

    # Pull hashes from static if available for the title block
    hashes = (static_analysis.get("hashes") or {}) if static_analysis else {}
    md5    = hashes.get("md5",  sample_meta.get("md5",  ""))
    sha1   = hashes.get("sha1", sample_meta.get("sha1", ""))

    # Screenshot guidance — tell Claude to write the subsection text when images
    # were captured and judged worth including.  The actual images are injected
    # by the PDF renderer; Claude only needs to write the prose/caption.
    sa = (dynamic_analysis or {}).get("screenshot_analysis") or {}
    if sa.get("include_in_report") and sa.get("caption"):
        screenshot_guidance = (
            "\n\nSCREENSHOT NOTE: The dynamic-analysis phase captured detonation "
            "screenshots and judged them worth including. In the Dynamic Analysis "
            "section of the technical report, add a '### Detonation Screenshots' "
            "subsection containing exactly this caption as a paragraph (verbatim): "
            f"\"{sa['caption']}\"\n"
            "Follow the caption with the line: "
            "`*(Screenshot frames embedded in the PDF/HTML version of this report.)*`"
        )
    else:
        screenshot_guidance = ""

    # Internal correlation hint — only included when matches exist so default reports
    # are byte-for-byte identical to before.
    internal_matches = (
        ((attribution or {}).get("internal_correlation") or {}).get("matches") or []
    )
    if internal_matches:
        match_summary = "; ".join(
            f"{m['matched_value']} (confidence={m['confidence']})"
            for m in internal_matches[:6]
        )
        internal_guidance = (
            "\n\nINTERNAL CORRELATION NOTE: The correlation phase matched "
            f"{len(internal_matches)} indicator(s) from this sample against the "
            "organization's internal IOC database. Add a "
            "'## Historical / Internal Correlation' section to the report, placed "
            "immediately after the Attribution section. Describe what the matches "
            "imply — repeat adversary, same campaign, TTPs re-use, etc. Use the "
            "'ai_interpretation' field from the attribution.internal_correlation "
            "block as the analytical basis. "
            f"Matched indicators: {match_summary}."
        )
    else:
        internal_guidance = ""

    # Static provenance note — only added when analyst provided their own findings.
    static_source = (static_analysis or {}).get("source", "")
    if static_source == "analyst-provided":
        static_provenance = (
            "\n\nSTATIC PROVENANCE NOTE: The static_analysis block was analyst-provided "
            "(not generated by the platform's own tools). In the Static Analysis section "
            "of the report, include the sentence: "
            "\"Note: Static findings for this sample were analyst-provided.\""
        )
    else:
        static_provenance = ""

    # Dynamic provenance note — only added when analyst provided their own sandbox findings.
    dynamic_source = (dynamic_analysis or {}).get("source", "")
    if dynamic_source == "analyst-provided":
        dynamic_provenance = (
            "\n\nDYNAMIC PROVENANCE NOTE: The dynamic_analysis block was analyst-provided "
            "(not generated by the platform's sandbox). In the Dynamic Analysis section "
            "of the report, include the sentence: "
            "\"Note: Dynamic findings for this sample were analyst-provided.\""
        )
    else:
        dynamic_provenance = ""

    # OSINT provenance note — only added when analyst uploaded their own OSINT findings.
    osint_source = (osint or {}).get("source", "")
    if osint_source == "analyst-provided":
        osint_provenance = (
            "\n\nOSINT PROVENANCE NOTE: The OSINT block was analyst-provided "
            "(the platform's OSINT phase was bypassed). In the OSINT section "
            "of the report, include the sentence: "
            "\"Note: OSINT findings for this case were analyst-provided.\""
        )
    else:
        osint_provenance = ""

    return f"""\
## Sample metadata
- Name: {name}
- SHA-256: {sha256 or "(unknown)"}
- MD5: {md5 or "(unknown)"}
- SHA-1: {sha1 or "(unknown)"}
- Route: {route}

## Phase availability
The following phases fed into this report. Where a phase is ABSENT, its section \
must say "Not available — phase did not run or failed" rather than being omitted \
or padded:
{_phase_summary(static_analysis, dynamic_analysis, osint, attribution, detection)}

{_phase_block(static_analysis,  "Static analysis")}

{_phase_block(dynamic_analysis, "Dynamic analysis")}

{_phase_block(osint,            "OSINT")}

{_phase_block(attribution,      "Attribution")}

{_phase_block(detection,        "Detection")}

IMPORTANT — output format (this overrides the JSON output block in the system prompt):
Return ONLY the raw Markdown report, beginning with the "# " title line and following \
the template exactly. No JSON wrapper, no code fences around the report, no preamble \
or postscript — just the report itself, starting with "# Malware Analysis Report: {name}".{screenshot_guidance}{internal_guidance}{static_provenance}{dynamic_provenance}{osint_provenance}"""


# ── Markdown helpers ──────────────────────────────────────────────────────────

def _strip_fences(text: str) -> str:
    """Remove a single outer code-fence wrapper if Claude added one."""
    stripped = text.strip()
    m = re.match(r"^```(?:markdown)?\s*\n([\s\S]*?)\n```\s*$", stripped)
    if m:
        return m.group(1).strip()
    return stripped


def _extract_title(markdown: str) -> str:
    """Return the text of the first H1 line; fallback if none found."""
    for line in markdown.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return "Malware Analysis Report"


# ── debug dump ────────────────────────────────────────────────────────────────

_DEBUG_DUMP_PATH = "/tmp/report_raw_debug.txt"


def _dump_raw(response: str) -> None:
    """Write the full raw response to a debug file for offline inspection."""
    try:
        with open(_DEBUG_DUMP_PATH, "w", encoding="utf-8") as fh:
            fh.write(response)
        import sys as _sys
        print(f"[report_debug] full raw response written to {_DEBUG_DUMP_PATH}", file=_sys.stderr)
    except OSError:
        pass  # never let debug I/O break the caller


# ── public entry point ────────────────────────────────────────────────────────

def generate_report(
    static_analysis: dict,
    dynamic_analysis: dict,
    osint: dict,
    attribution: dict,
    detection: dict,
    sample_meta: dict,
) -> dict:
    """
    Generate the dual-audience threat-intelligence report.

    Parameters
    ----------
    static_analysis / dynamic_analysis / osint / attribution / detection:
        Phase blocks from the case file (may be {} if a phase failed).
    sample_meta:
        {"name": str, "sha256": str, "route": str}

    Returns
    -------
    dict
        {"report": {"format": "markdown", "content": "<raw markdown>",
                    "title": "<first H1>", "overall_confidence": "<str>",
                    "file_path": ""}}
        On failure: {"_parse_error": True, "error": str}
    """
    system_prompt = _build_system_prompt()
    user_message  = _build_user_message(
        static_analysis, dynamic_analysis, osint, attribution, detection, sample_meta
    )

    raw_response = call_claude(
        system_prompt=system_prompt,
        user_content=user_message,
        max_tokens=settings.report_max_tokens,
    )

    content = _strip_fences(raw_response)

    if not content:
        _dump_raw(raw_response)
        return {
            "_parse_error": True,
            "error": "Empty response from Claude.",
            "_raw_response": raw_response[:2000],
        }

    title      = _extract_title(content)
    confidence = (attribution or {}).get("overall_confidence", "")

    return {
        "report": {
            "format":             "markdown",
            "content":            content,
            "title":              title,
            "overall_confidence": confidence,
            "file_path":          "",
        }
    }


# ── CLI ───────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import argparse
    import sys
    from pathlib import Path

    parser = argparse.ArgumentParser(
        description="Report generator — offline test on a saved case file",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  python -m backend.app.services.report_generator \\\n"
            "      --case test_fixtures/agenttesla_case.json\n"
        ),
    )
    parser.add_argument(
        "--case", metavar="PATH", required=True,
        help="Path to a saved case JSON file (output of dump_case.py).",
    )
    args = parser.parse_args()

    case_path = Path(args.case)
    if not case_path.exists():
        print(f"[!] File not found: {case_path}", file=sys.stderr)
        sys.exit(1)

    try:
        case = json.loads(case_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        print(f"[!] Invalid JSON in {case_path}: {exc}", file=sys.stderr)
        sys.exit(1)

    static_analysis  = case.get("static_analysis")  or {}
    dynamic_analysis = case.get("dynamic_analysis") or {}
    osint            = case.get("osint")            or {}
    attribution      = case.get("attribution")      or {}
    detection        = case.get("detection")        or {}

    sample = case.get("sample") or {}
    sha256 = (
        (sample.get("extracted_primary_hashes") or {}).get("sha256")
        or sample.get("sha256", "")
    )
    sample_meta = {
        "name":   sample.get("name", case_path.stem),
        "sha256": sha256,
        "md5":    sample.get("md5",  ""),
        "sha1":   sample.get("sha1", ""),
        "route":  case.get("route", "unknown"),
    }

    for label, block in [
        ("static_analysis",  static_analysis),
        ("dynamic_analysis", dynamic_analysis),
        ("osint",            osint),
        ("attribution",      attribution),
        ("detection",        detection),
    ]:
        status = "present" if block else "ABSENT"
        print(f"  [{status:7s}] {label}", file=sys.stderr)

    print("[*] Calling Claude for report generation …", file=sys.stderr)

    result = generate_report(
        static_analysis, dynamic_analysis, osint, attribution, detection, sample_meta
    )

    # Pretty-print but keep report.content readable (don't double-escape)
    if "report" in result and "content" in result["report"]:
        content = result["report"].pop("content")
        print(json.dumps(result, indent=2, default=str))
        print()
        print("=== REPORT CONTENT ===")
        print(content)
    else:
        print(json.dumps(result, indent=2, default=str))
